### PR TITLE
add latitude / logitude position into workout file when using .rlv whith a coresponding .tcx file

### PR DESCRIPTION
**Pull request by PiR43**
Positions are taking at same distance of the tcx and rlv file so tcx must be the same parcours of video but no need to have the same time. tested with http://cyclingrlv.com/rlvs/es_lagos_de_covadonga/ and http://ridewithgps.com/routes/2037900.tcx

### CODE REVIEW

**Comment by davidzof** [comment]
I'm looking at using the same idea for TTS format files that are missing GPS data. I'm wondering whether a percentage through file should be used, rather than distance, in case the two files don't match in length exactly?

**Comment by PiR43** [comment]
For manage rlv file whith a diferent length I have added the following code:
commit https://github.com/PiR43/wattzap-ce/commit/ab8873a6c52c5062edb1c8eb652b6f915c6ed59e lines 143-148
<code>
+ double pgmfDist = pgmfSegment.get(pgmfSegment.size()-1).getDistanceFromStart();
	+ double tcxDist = tcxSegment.get(tcxSegment.size()-1).getDistanceFromStart();
	+ logger.debug("pgmd Dist: "+pgmfDist+" tcx distance: "+tcxDist);
	+ for(int i=0; i<tcxSegment.size(); i++){
	+ tcxSegment.get(i).setDistanceFromStart(tcxSegment.get(i).getDistanceFromStart()*pgmfDist/tcxDist);
	+ }
</code>


Now I have working on another feature who use tcx files : display advance or delay comparing to virtual partners (virtual partner are calculate from over tcx files who can come from another wazzap training or even a real training). It works on simulation (DummySpeed) but I still need test it on hometrainer before commit it.

**Comment by davidzof** [comment]
I had to merge this change manually in the end. I've got code into TTSReader to produce a GPX file from lat/lon/alt data so we can display a map, I will see if I can merge this with RLVReader.

**Comment by davidzof** [comment]
Ok the latest RLVReader adds mapping information. Obviously it is not exact but give an idea of where you are on the road.

**Pull request closed without merging**
